# Generated by Django 3.1.3 on 2020-11-18 15:00

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_description', models.CharField(max_length=100)),
                ('category_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories Products',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_permission', models.CharField(choices=[('Adm', 'Administrativo'), ('Chef', 'Cocinero'), ('Mes', 'Mesero')], max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Permissions',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('list_price', models.IntegerField()),
                ('image_prod', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('categoriesproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.categoriesproduct')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Suppliers',
            },
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('zip_code', models.IntegerField(null=True)),
                ('slogan', models.CharField(max_length=150, null=True)),
                ('sitio_web', models.CharField(max_length=100, null=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Stores',
            },
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.products')),
                ('stores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.stores')),
            ],
            options={
                'verbose_name_plural': 'Stocks',
            },
        ),
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(blank=True)),
                ('active', models.BooleanField(default=True, null=True, verbose_name='active')),
                ('imagen_staf', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('permission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.permission')),
                ('stores', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.stores')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Staffs',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='stores',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.stores'),
        ),
        migrations.AddField(
            model_name='products',
            name='suppliers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.suppliers'),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.IntegerField()),
                ('order_date', models.DateField()),
                ('staffs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.staffs')),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='ItemsOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('list_price', models.IntegerField()),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.orders')),
            ],
            options={
                'verbose_name_plural': 'Items Order',
            },
        ),
    ]
