# Generated by Django 3.1.3 on 2020-11-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='suppliers',
        ),
        migrations.AlterField(
            model_name='products',
            name='list_price',
            field=models.FloatField(),
        ),
    ]
