# Generated by Django 3.1.3 on 2020-11-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201124_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='list_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
