# Generated by Django 3.1.2 on 2020-10-30 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories_product',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='order_items',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='permission_id',
        ),
        migrations.RemoveField(
            model_name='products',
            name='products_id',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='staff_id',
        ),
        migrations.RemoveField(
            model_name='stores',
            name='stores_id',
        ),
        migrations.RemoveField(
            model_name='suppliers',
            name='suppliers_id',
        ),
    ]
