# Generated by Django 3.1.2 on 2020-10-30 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebApp', '0002_auto_20201030_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffs',
            old_name='permissions',
            new_name='permissions_id',
        ),
    ]
