# Generated by Django 3.1.2 on 2020-10-31 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories_product',
            new_name='CategoriesProduct',
        ),
        migrations.RenameModel(
            old_name='Items_order',
            new_name='ItemsOrder',
        ),
    ]
